---
abstract: 'Talk to a Mastodon server'
author:
  - 'José Joaquín Atria <jjatria@cpan.org>'
build_requires:
  Plack: '1.0043'
  Test::Exception: '0.043'
  Test::More: '1.302078'
  Test::Pod: '1.51'
  Test::TCP: '2.17'
  Test::Warnings: '0.026'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mastodon-Client
provides:
  Mastodon::Client:
    file: lib/Mastodon/Client.pm
    version: '0.009'
  Mastodon::Entity::Account:
    file: lib/Mastodon/Entity/Account.pm
    version: '0.009'
  Mastodon::Entity::Application:
    file: lib/Mastodon/Entity/Application.pm
    version: '0.009'
  Mastodon::Entity::Attachment:
    file: lib/Mastodon/Entity/Attachment.pm
    version: '0.009'
  Mastodon::Entity::Card:
    file: lib/Mastodon/Entity/Card.pm
    version: '0.009'
  Mastodon::Entity::Context:
    file: lib/Mastodon/Entity/Context.pm
    version: '0.009'
  Mastodon::Entity::Error:
    file: lib/Mastodon/Entity/Error.pm
    version: '0.009'
  Mastodon::Entity::Instance:
    file: lib/Mastodon/Entity/Instance.pm
    version: '0.009'
  Mastodon::Entity::Mention:
    file: lib/Mastodon/Entity/Mention.pm
    version: '0.009'
  Mastodon::Entity::Notification:
    file: lib/Mastodon/Entity/Notification.pm
    version: '0.009'
  Mastodon::Entity::Relationship:
    file: lib/Mastodon/Entity/Relationship.pm
    version: '0.009'
  Mastodon::Entity::Report:
    file: lib/Mastodon/Entity/Report.pm
    version: '0.009'
  Mastodon::Entity::Results:
    file: lib/Mastodon/Entity/Results.pm
    version: '0.009'
  Mastodon::Entity::Status:
    file: lib/Mastodon/Entity/Status.pm
    version: '0.009'
  Mastodon::Entity::Tag:
    file: lib/Mastodon/Entity/Tag.pm
    version: '0.009'
  Mastodon::Listener:
    file: lib/Mastodon/Listener.pm
    version: '0.009'
  Mastodon::Role::Entity:
    file: lib/Mastodon/Role/Entity.pm
    version: '0.009'
  Mastodon::Role::UserAgent:
    file: lib/Mastodon/Role/UserAgent.pm
    version: '0.009'
  Mastodon::Types:
    file: lib/Mastodon/Types.pm
    version: '0.009'
requires:
  AnyEvent: '7.13'
  AnyEvent::Emitter: '0.02'
  AnyEvent::HTTP: '2.23'
  DateTime: '1.42'
  DateTime::Format::Strptime: '1.73'
  JSON::MaybeXS: '1.003009'
  LWP::UserAgent: '6.25'
  List::Util: '1.47'
  Log::Any: '1.049'
  Moo: '2.003002'
  Try::Tiny: '0.28'
  Type::Params: '1.000006'
  Types::Common::String: '1.000006'
  Types::Path::Tiny: '0.005'
  Types::Standard: '1.000006'
  URI: '1.71'
  perl: '5.010'
resources:
  bugtracker: https://gitlab.com/jjatria/Mastodon-Client/issues
  repository: git://gitlab.com/jjatria/Mastodon-Client.git
version: '0.009'
x_serialization_backend: 'YAML::Tiny version 1.70'
