---
abstract: 'Talk to a Mastodon server'
author:
  - 'José Joaquín Atria <jjatria@cpan.org>'
build_requires:
  Test::Exception: '0.043'
  Test::More: '1.302078'
  Test::Warnings: '0.026'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mastodon-Client
requires:
  AnyEvent::Emitter: '0.02'
  DateTime: '1.42'
  LWP::UserAgent: '6.25'
  List::Util: '1.47'
  Log::Any: '1.049'
  Moo: '2.003002'
  Try::Tiny: '0.28'
  Type::Params: '1.000006'
  Types::Common::String: '1.000006'
  Types::Path::Tiny: '0.005'
  Types::Standard: '1.000006'
  URI: '1.71'
resources:
  bugtracker: https://gitlab.com/jjatria/Mastodon-Client/issues
  repository: git://gitlab.com/jjatria/Mastodon-Client.git
version: '0.003'
x_serialization_backend: 'YAML::Tiny version 1.70'
